/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpectateRouteImport } from './routes/spectate'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpectateIndexRouteImport } from './routes/spectate.index'
import { Route as SpectateIdRouteImport } from './routes/spectate.$id'
import { Route as PlayModeRouteImport } from './routes/play.$mode'

const SpectateRoute = SpectateRouteImport.update({
  id: '/spectate',
  path: '/spectate',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectateIndexRoute = SpectateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpectateRoute,
} as any)
const SpectateIdRoute = SpectateIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpectateRoute,
} as any)
const PlayModeRoute = PlayModeRouteImport.update({
  id: '/play/$mode',
  path: '/play/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/spectate': typeof SpectateRouteWithChildren
  '/play/$mode': typeof PlayModeRoute
  '/spectate/$id': typeof SpectateIdRoute
  '/spectate/': typeof SpectateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/play/$mode': typeof PlayModeRoute
  '/spectate/$id': typeof SpectateIdRoute
  '/spectate': typeof SpectateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/spectate': typeof SpectateRouteWithChildren
  '/play/$mode': typeof PlayModeRoute
  '/spectate/$id': typeof SpectateIdRoute
  '/spectate/': typeof SpectateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/spectate'
    | '/play/$mode'
    | '/spectate/$id'
    | '/spectate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/play/$mode'
    | '/spectate/$id'
    | '/spectate'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/spectate'
    | '/play/$mode'
    | '/spectate/$id'
    | '/spectate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SpectateRoute: typeof SpectateRouteWithChildren
  PlayModeRoute: typeof PlayModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spectate': {
      id: '/spectate'
      path: '/spectate'
      fullPath: '/spectate'
      preLoaderRoute: typeof SpectateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectate/': {
      id: '/spectate/'
      path: '/'
      fullPath: '/spectate/'
      preLoaderRoute: typeof SpectateIndexRouteImport
      parentRoute: typeof SpectateRoute
    }
    '/spectate/$id': {
      id: '/spectate/$id'
      path: '/$id'
      fullPath: '/spectate/$id'
      preLoaderRoute: typeof SpectateIdRouteImport
      parentRoute: typeof SpectateRoute
    }
    '/play/$mode': {
      id: '/play/$mode'
      path: '/play/$mode'
      fullPath: '/play/$mode'
      preLoaderRoute: typeof PlayModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpectateRouteChildren {
  SpectateIdRoute: typeof SpectateIdRoute
  SpectateIndexRoute: typeof SpectateIndexRoute
}

const SpectateRouteChildren: SpectateRouteChildren = {
  SpectateIdRoute: SpectateIdRoute,
  SpectateIndexRoute: SpectateIndexRoute,
}

const SpectateRouteWithChildren = SpectateRoute._addFileChildren(
  SpectateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SpectateRoute: SpectateRouteWithChildren,
  PlayModeRoute: PlayModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
