use hmac::Hmac;
use pbkdf2::pbkdf2;
use rand::RngCore;
use sha2::Sha256;
use subtle::ConstantTimeEq;

const ITERATIONS: u32 = 210_000;

pub fn hash_password(password: &str) -> String {
    let mut salt = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut salt);
    let salt_hex = hex::encode(salt);
    let digest_hex = derive(password, &salt);
    format!("pbkdf2_sha256${ITERATIONS}${salt_hex}${digest_hex}")
}

pub fn verify_password(password: &str, encoded: &str) -> bool {
    let parts: Vec<&str> = encoded.splitn(4, '$').collect();
    if parts.len() != 4 || parts[0] != "pbkdf2_sha256" {
        return false;
    }
    let iterations: u32 = match parts[1].parse() {
        Ok(n) => n,
        Err(_) => return false,
    };
    let salt = match hex::decode(parts[2]) {
        Ok(s) if !s.is_empty() => s,
        _ => return false,
    };
    let expected = match hex::decode(parts[3]) {
        Ok(e) if !e.is_empty() => e,
        _ => return false,
    };

    let mut output = vec![0u8; 32];
    pbkdf2::<Hmac<Sha256>>(password.as_bytes(), &salt, iterations, &mut output)
        .expect("PBKDF2 error");

    output.ct_eq(&expected).into()
}

fn derive(password: &str, salt: &[u8]) -> String {
    let mut output = vec![0u8; 32];
    pbkdf2::<Hmac<Sha256>>(password.as_bytes(), salt, ITERATIONS, &mut output)
        .expect("PBKDF2 error");
    hex::encode(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Hash generated by Python: hash_password("password", "deadbeefcafebabe0102030405060708")
    // python3 -c "
    //   import hashlib; s='deadbeefcafebabe0102030405060708'
    //   d=hashlib.pbkdf2_hmac('sha256','password'.encode(),bytes.fromhex(s),210000).hex()
    //   print(f'pbkdf2_sha256$210000${s}${d}')
    // "
    const KNOWN_HASH: &str =
        "pbkdf2_sha256$210000$deadbeefcafebabe0102030405060708$\
         286c2122641c6fbf425b0a75402e28be095e604bb1039dbce45889849f3ef88c";

    #[test]
    fn verify_known_python_hash() {
        assert!(verify_password("password", KNOWN_HASH));
    }

    #[test]
    fn wrong_password_fails() {
        assert!(!verify_password("wrong", KNOWN_HASH));
    }

    #[test]
    fn roundtrip() {
        let hash = hash_password("my-secret");
        assert!(verify_password("my-secret", &hash));
        assert!(!verify_password("wrong", &hash));
    }
}
